spring:
  redis:
    host: i10d205.p.ssafy.io
    port: 6379

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:mysql://i10d205.p.ssafy.io:3306/yut_db?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ssafy

  # ???? spring.io?? doc?? ??? ??????.
  # jpa??
  jpa:
    hibernate: # hibernate ?? ??
      # ?????? ?? ??? ???? ? ???, ?? ?? entity ??? ?? ?? ??? ?? ??
      # if exists drop table ??? ?? ?????? ?? ??.
      ddl-auto: update
    properties: # property ?? ??
      hibernate: # hibernate property ??
        format_sql: true

  jwt:
    secret: ssafyD205rlatnqlsdlwnaldlgmldnddidtjdrbqkrwlgnsdlwnsgmlghkdlxlddkwkdkwk
# ?? ?? ??
#logging:
#  level:
#    # hibernate ? ??? ?? ??? debug??? ??
#    # jpa hibernate? ???? sql? ??? ??? ???? ?? ??
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace # ?? ???? ????? ???? ??